sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.8
addons:
  apt:
    packages:
    - gnuplot
install:
  - source tools/setup_travis.sh $HOME/miniconda $TRAVIS_PYTHON_VERSION
  - python -V
  - export IMP_TMP_DIR=/tmp
script:
  - mkdir build
  - cd build
  - if test "${TRAVIS_PYTHON_VERSION}" = "2.7" ; then PY2=on; else PY2=off; fi
  - cmake .. -DIMP_DIR=${CONDA_PREFIX}/lib/cmake/IMP -DUSE_PYTHON2=${PY2}
  - make
  - ./setup_environment.sh ../test/nosetests --with-coverage --cover-branches -e 'probabilistic' ../test/test_*.py ../test/medium_test_*.py test/*/*.py > /dev/null
after_script:
  - bash <(curl -s https://codecov.io/bash)
